spring.profiles.active: development
---
spring:
  profiles: development
  application:
    name: tt-gateway
  resources:
      chain:
        enabled: true
security:
  signing-key: 1754@@$$GgRr@0oK%%*bvVLl1Wo0
  jwt:
    resource-ids: tt-gateway
zuul:
  sensitiveHeaders : ''
ribbon:
  ReadTimeout: 10000
logging:
  level:
    root: INFO

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
server:
  port: 8080
eureka:
  instance:
      preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
---
spring:
  profiles: production
  application:
    name: tt-gateway
  resources:
      chain:
        enabled: true
security:
  signing-key: 1754@@$$GgRr@0oK%%*bvVLl1Wo0
  jwt:
    resource-ids: tt-gateway
zuul:
  sensitiveHeaders : ''
ribbon:
  ReadTimeout: 10000
logging:
  level:
    root: INFO

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
server:
  port: 8080
eureka:
  instance:
      preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://www.toppertalks.com:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false