spring.profiles.active: development
---
spring:
  profiles: development
  application:
    name: ssp-gateway
  resources:
      chain:
        enabled: true
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://ssp-auth/me
      jwt:
        keyValue: 123
zuul:
  sensitiveHeaders : ''
ribbon:
  ReadTimeout: 10000
logging:
  level:
    root: INFO

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
server:
  port: 8080
eureka:
  instance:
      preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
---
spring:
  profiles: docker
  application:
    name: ssp-gateway
  resources:
      chain:
        enabled: true
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://ssp-auth/me
      jwt:
        keyValue: 123
zuul:
  sensitiveHeaders : ''
ribbon:
  ReadTimeout: 20000
logging:
  level:
    root: INFO

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
server:
  port: 8080
eureka:
  instance:
      preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ssp-discovery:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false